alias cls='clear'
alias df='df -h'
alias duu='du -sh'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias fname='func() { find -name *$1*;}; func'
alias grep='grep --color=auto'
alias l='ls -CF'
alias la='ls -A'
alias lh='ls -lh'
alias lha='lh -a'
alias ll='ls -alF'
alias ls='ls --color=auto'
alias md='mkdir -p'
alias psg='ps ax | grep'
alias rm='rm -rf'
alias upcls='./scripts/feeds clean'
alias upfeed='./scripts/feeds update -a'
alias upins='./scripts/feeds install -a'
alias upup='./scripts/feeds update -a && ./scripts/feeds install -a'
