name: R1S_H5_ttt 调试专用

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'true'

env:
  #REPO_URL: https://github.com/coolsnowwolf/lede
  #REPO_BRANCH: master
  #FEEDS_CONF: feeds.conf.default
  #CONFIG_FILE: config.lede
  DIY_P1_SH: diy-p1.sh
  #DIY_P2_SH: diy-p2.sh
  #DIY_P3_SH: diy-p3.sh
  #DIY_P4_SH: diy-p4.sh
  #UPLOAD_BIN_DIR: false
  #UPLOAD_FIRMWARE: false
  #UPLOAD_COWTRANSFER: false
  #UPLOAD_WETRANSFER: false
  #UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          # 第一部分：环境部署和源码下载
          chmod +x $DIY_P1_SH
          $GITHUB_WORKSPACE/$DIY_P1_SH

      - name: SSH connection to Actions
        uses: Dboykey/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
